// Code generated by "stringer -type=Status,Mode"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WaitingForOpponent-0]
	_ = x[PlayerXTurn-1]
	_ = x[PlayerOTurn-2]
	_ = x[PlayerXWon-3]
	_ = x[PlayerOWon-4]
	_ = x[Draw-5]
}

const _Status_name = "WaitingForOpponentPlayerXTurnPlayerOTurnPlayerXWonPlayerOWonDraw"

var _Status_index = [...]uint8{0, 18, 29, 40, 50, 60, 64}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PvP-1]
	_ = x[PvE-2]
}

const _Mode_name = "PvPPvE"

var _Mode_index = [...]uint8{0, 3, 6}

func (i Mode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
